#!/bin/sh
# postinst script for lazyctrl

SHORTCUT_NAME=$HOME/.config/autostart/lazyctrl.desktop

echo "[Desktop Entry]" > $SHORTCUT_NAME
echo "Encoding=UTF-8" >> $SHORTCUT_NAME
echo "Type=Application" >> $SHORTCUT_NAME
echo "Name=LazyCtrl" >> $SHORTCUT_NAME
echo "Comment='Quick access utility'" >> $SHORTCUT_NAME
echo "Exec=/opt/lazyctrl/lazyctrl" >> $SHORTCUT_NAME
echo "StartupNotify=false" >> $SHORTCUT_NAME
echo "Terminal=false" >> $SHORTCUT_NAME
echo "Path=/opt/lazyctrl/lazyctrl" >> $SHORTCUT_NAME

exit 0
